export const ERROR_GEOLOCATION_HANDLER = "ERROR_WEATHER_HANDLER";
export const SET_GEOLOCATION = "SET_GEOLOCATION";
export const SET_GEOCODE = "SET_GEOCODE";
export const BEGIN_UPDATE = "BEGIN_UPDATE";
export const SET_WEATHER = "SET_WEATHER";
export const SET_HISTORY_DATA = "SET_HISTORY_DATA";

export const GET_HISTORY_DATA = "GET_HISTORY_DATA";
export const UPDATE_HISTORY_DATA = "UPDATE_HISTORY_DATA";
